<div class="admin-form-grid"><div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-video"></i></div><div><p class="form-card-title">Video Details</p><p class="form-card-subtitle">URL, thumbnail and description</p></div></div><div class="form-card-body">
<div class="field-group"><label class="field-label">Title</label><input name="title" class="field-input" required value="{{ old('title', $awarenessVideo->title ?? '') }}"></div>
<div class="field-group"><label class="field-label">Video URL</label><input type="url" name="video_url" class="field-input" required value="{{ old('video_url', $awarenessVideo->video_url ?? '') }}"></div>
<div class="field-group"><label class="field-label">Thumbnail URL</label><input type="url" name="thumbnail_image" class="field-input" value="{{ old('thumbnail_image', $awarenessVideo->thumbnail_image ?? '') }}"></div>
<div class="field-group"><label class="field-label">Short Description</label><textarea name="short_description" class="field-input" rows="4">{{ old('short_description', $awarenessVideo->short_description ?? '') }}</textarea></div>
</div></div><div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-cog"></i></div><div><p class="form-card-title">Publish</p><p class="form-card-subtitle">Status and sorting</p></div></div><div class="form-card-body">
<div class="field-group"><label class="field-label">Sort Order</label><input type="number" name="sort_order" class="field-input" value="{{ old('sort_order', $awarenessVideo->sort_order ?? 0) }}"></div>
<label class="role-checkbox-item"><input type="checkbox" name="status" value="1" class="role-checkbox" {{ old('status', $awarenessVideo->status ?? true) ? 'checked' : '' }}><div class="check-icon"></div><span class="checkbox-text">Active</span></label>
</div></div></div><div class="form-actions"><button class="btn-primary"><i class="fas fa-save"></i> Save Video</button><a href="{{ route('admin.awareness-videos.index') }}" class="btn-ghost">Cancel</a></div>
